[package]
name = "dungeon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lumenpyx = { path = "../../../lumenpyx"}
rand = "0.8.5"
rustc-hash = "1.1.0"
